### ISSUE TITLE
[BUG] Integration Tests Fail With OpenStack

### ISSUE THREAD

**Issue by irishgordo** [harvester/vm-import-controller#8]
## Description 
Trying to run integration tests via `go test -v ./tests/integration/` - the integration tests fail on OpenStack "Zed".

```YAML
  Timed out after 120.000s.
  Unexpected error:
      <*errors.StatusError | 0xc0004aa640>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "persistentvolumeclaims \"k3os-zed-openstack-test-0\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "k3os-zed-openstack-test-0",
                  Group: "",
                  Kind: "persistentvolumeclaims",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
      persistentvolumeclaims "k3os-zed-openstack-test-0" not found
  occurred
  In [It] at: /home/mike/Projects/vm-import-controller/tests/integration/openstack_test.go:98
```

On the Image downloading portion:
![Screenshot from 2022-10-26 16-38-41](https://user-images.githubusercontent.com/5370752/198354766-1633703f-1665-4b19-b556-fc3a8d0d85a2.png)
![Screenshot from 2022-10-26 16-37-42](https://user-images.githubusercontent.com/5370752/198354772-7b244497-f8ee-453f-9bd4-d3b562d4ad25.png)

The error message seems to note that it is trying to fetch it over `https` when it is not really, clicking into the image, you'll see the url is accurate at the `http` address with port `8080`.

cc: @ibrokethecloud
